version: '3.8'

services:
  crm-backend:
    image: laravelphp/php-fpm
    container_name: crm-backend
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    networks:
      - crm-network
    environment:
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=crm_db
      - DB_USERNAME=root
      - DB_PASSWORD=root

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - crm-network
    ports:
      - "3308:3306"

networks:
  crm-network:
    driver: bridge

volumes:
  mysql-data:
