version: '3.8'

services:
  crm-backend:
    build:
      context: .  # Corrigez ce chemin
      dockerfile: Dockerfile  # Assurez-vous que le fichier Dockerfile est bien à cet emplacement
    container_name: crm-backend
    ports:
      - "8000:80"  # Le port 8000 local vers le port 80 du conteneur Apache
    networks:
      - crm-network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=crm-backend
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: crm-db
    environment:
      MYSQL_ROOT_PASSWORD: passer
      MYSQL_DATABASE: crm-backend
    ports:
      - "3308:3306"
    networks:
      - crm-network

  crm-frontend:
    build:
      context: ../crm-frontend  # Spécifiez le bon répertoire contenant Dockerfile pour le frontend
    container_name: crm-frontend
    ports:
      - "4200:80"
    networks:
      - crm-network
    depends_on:
      - crm-backend

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"  # Le port 8080 pour accéder à Jenkins
      - "50000:50000"  # Port pour les agents Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home  # Persistance des données Jenkins
      - /var/run/docker.sock:/var/run/docker.sock  # Monture du socket Docker pour permettre à Jenkins d'accéder à Docker
    networks:
      - crm-network
    environment:
      JENKINS_OPTS: --httpPort=8080

networks:
  crm-network:
    driver: bridge

volumes:
  jenkins_home:
